In [87]:
with open("OperacionesVectores") as f:
    for line in f:
        print(line, end='')


clear 
close all
clc
q = randi(20,1,4)
entrenamiento = randi(20,10,4)
%% ejemplo 1
distancias = [];
for i = 1:size(entrenamiento,1)
    z_q_entr_i =q-entrenamiento(i,:);
    dista = (z_q_entr_i*z_q_entr_i')^(1/2);
    distancias = [distancias;dista];
end
distancias
%% ejemplo 2
Q =repmat(q,size(entrenamiento,1),1)
Z = Q-entrenamiento
S_con_basurita = Z*Z';
distancias_S = (diag(S_con_basurita)).^(1/2)
%% ejemplo 3
S_funcion = dist(entrenamiento,q')


In [ ]:
import numpy as np
import scipy.spatial as dis

q = np.random.randint(20, size=(1, 4))                      
entrenamiento = np.random.randint(20, size=(10, 4))
#Ejemplo 1
distancia = []
print(f"Datos de query:\n{q}\n\nDatos de entrenamiento:\n{entrenamiento}\n")

for i in range(entrenamiento.shape[0]):
    z_q_entr_i = q[0,:] - entrenamiento[i,:]
    dista = (z_q_entr_i @ z_q_entr_i.T) ** (1/2) # -> (1, 4) * (4, 1) = (1,1) -> (1, 1) ** .5 
    distancia.append(dista)

print("Distancias ejercicio 1:")
for d in distancia:
    print(d)
print()
#Ejemplo 2
Q = np.tile(q,(entrenamiento.shape[0],1))
print(f'Matriz Q:\n{Q}\n')
Z = Q - entrenamiento
print(f'Matriz Z:\n{Z}\n')
S_with_garbage = Z @ Z.T
print(f'Matriz con basura:\n{S_with_garbage}\n')
distancias_S = np.diag(S_with_garbage) ** (1/2)

print("Distancias ejercicio 2:")
for d in distancias_S:
    print(d)

Datos de query:
[[16 17 13 16]]

Datos de entrenamiento:
[[18  4  9  4]
 [ 4 16 12  3]
 [14  3 10 11]
 [17  8  4  6]
 [15 17 15  5]
 [10  3 14  5]
 [ 6 13  4 15]
 [19  0  3  7]
 [ 6  9 15 18]
 [13 12  4 13]]

Distancias ejercicio 1:
18.24828759089466
17.74823934929885
15.297058540778355
16.217274740226856
11.224972160321824
18.81488772222678
14.071247279470288
21.88606862823929
13.114877048604
11.135528725660043

Matriz Q:
[[16 17 13 16]
 [16 17 13 16]
 [16 17 13 16]
 [16 17 13 16]
 [16 17 13 16]
 [16 17 13 16]
 [16 17 13 16]
 [16 17 13 16]
 [16 17 13 16]
 [16 17 13 16]]

Matriz Z:
[[-2 13  4 12]
 [12  1  1 13]
 [ 2 14  3  5]
 [-1  9  9 10]
 [ 1  0 -2 11]
 [ 6 14 -1 11]
 [10  4  9  1]
 [-3 17 10  9]
 [10  8 -2 -2]
 [ 3  5  9  3]]

Matriz con basura:
[[333 149 250 275 122 298  80 375  52 131]
 [149 315 106 136 153 228 146 108 100  89]
 [250 106 234 201  51 260 108 307 116 118]
 [275 136 201 263  91 221 117 336  24 153]
 [122 153  51  91 126 129   3  76  -8  18]
 [298 228 260 221 129 354

In [ ]:
Q = np.tile(q,(entrenamiento.shape[0],1))
print(f'Matriz Q:\n{Q}\n')
Z = Q - entrenamiento
print(f'Matriz Z:\n{Z}\n')
S_with_garbage = Z @ Z.T
print(f'Matriz con basura:\n{S_with_garbage}\n')
distancias_S = np.diag(S_with_garbage) ** (1/2)                                                     #por cada query iteraremos por todos los elementos del entrenamiento 
        distancia = 0                                                               
        for k in range(cols_dn):                                                    
            distancia += (query_samples.iloc[j,k] - training_samples.iloc[i,k]) ** 2
            distancia **= 1/2
        d_i.append(distancia)